### ISSUE TITLE
Teacher Week 4 Review

### ISSUE THREAD

**Issue by DerekBokelman** [katiehickman/flask_portfolio#36]

**Comment by jm1021** [comment]
Kate and Sreya are PBL coding.  Kian is on final video.  All are doing binary labs and hacks.   1.0

**Comment by jm1021** [comment]
Individual work.  There is a big gap between work Katie and Sreya are peforming vs what I see from Derek and Kian.  Derek seem to have pulled a file into to repository.  It is really unclear what I am clicking on with Kian.
Katie and Sriya are much better.
Katie 2/2
Sriya 2/2
Derek 1/2
Kian 1/2

**Comment by jm1021** [comment]
Team, README has ended up being a paragraph and links per person.  It is hard to see overall picture.  You still have you original design, but I am not seeing how ASCII and some other concepts we are learning are fitting in.  Review README I posted on Twitter.  2/2 for team, 0.5 of 1 for planning

**Comment by jm1021** [comment]
My advice is that Kian and Derek go back and do some old labs in their workspace.  Also, I think you should rotate Scrum Master, which is supposed to be 10 minutes a day to another person.
